### ISSUE TITLE
Website Navigation Issue: Smooth Scrolling Dysfunctionality During Loading

### ISSUE THREAD

**Issue by isaka-james** [murtuja43/murtuja43.github.io#2]
**Issue Description:**
Upon testing the website on multiple browsers including Brave, Firefox, and Chrome, it was observed that the smooth scrolling functionality for the #footer, #about, #portfolio, and #blog sections did not work as expected. Despite implementing smooth scrolling, these sections fail to navigate while the website is loading. Only the #home section appears to function correctly during this phase.

**Steps to Reproduce:**
1. Open the website [https://murtuja43.github.io/](https://murtuja43.github.io/).
2. While the website is loading, attempt to navigate to the #footer, #about, #portfolio, or #blog sections by clicking on their respective links.
3. Observe that these links do not trigger smooth scrolling as intended.

**Suggestion:**
- Consider implementing lazy loading for the entire website to enhance user experience, especially during the loading phase. This ensures that all features become accessible once the website has fully loaded.
- Review the logic for smooth scrolling implementation, ensuring it is integrated directly within the main page rather than within includes. This adjustment may resolve the issue with hrefs not functioning properly.

**Comment by murtuja43** [comment]
Hi @isaka-james 

Thank you for taking the time to thoroughly test the website on multiple browsers and for reporting the issue with smooth scrolling. I appreciate your detailed feedback.

I'll address this problem as soon as possible. Currently, I'm occupied with another project, but I should be able to work on this issue next week. I will close this issue after fixing the problem.

Best regards,
Murtuja Kayes

**Comment by isaka-james** [comment]
Okay if you are currently much occupied, I will try to fork and make pull request fixing some performance issues.
